version: '3.8'

services:
  # migration:
  #   build:
  #     dockerfile: dockerfile
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 15s
  #       max_attempts: 5
  #       window: 10s
  #   environment:
  #     - PB_APPLICATION_STAGE=DOCKER
  #   command: /bin/sh -c "aerich upgrade"
  #   volumes:
  #     - .:/usr/src
  #   depends_on:
  #     - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devdb
      - POSTGRES_PASSWORD=password
    ports:
      - "5440:5432"
    volumes:
      - db-dev:/var/lib/postgresql/data

volumes:
  db-dev: {}